---
sidebar: sidebar 
permalink: tanzu/vtwn-solution-overview.html 
keywords: VMware Tanzu, Tanzu, DevOps, Netapp, Trident, Trident Protect 
summary: 'Este documento de referência fornece validação de implantação de diferentes versões de soluções VMware Tanzu Kubernetes, implantadas como Tanzu Kubernetes Grid (TKG), Tanzu Kubernetes Grid Service (TKGS) ou Tanzu Kubernetes Grid Integrated (TKGI) em vários ambientes de data center diferentes, conforme validados pela NetApp.' 
---
= NVA-1166: VMware Tanzu com NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Alan Cowles e Nikhil M Kulkarni, NetApp

[role="lead"]
Este documento de referência fornece validação de implantação de diferentes versões de soluções VMware Tanzu Kubernetes, implantadas como Tanzu Kubernetes Grid (TKG), Tanzu Kubernetes Grid Service (TKGS) ou Tanzu Kubernetes Grid Integrated (TKGI) em vários ambientes de data center diferentes, conforme validados pela NetApp.  Ele também descreve a integração de armazenamento com os sistemas de armazenamento NetApp e o orquestrador de armazenamento Trident para o gerenciamento de armazenamento persistente e o Trident Protect para backup e clonagem de aplicativos com estado usando esse armazenamento persistente.  Por fim, o documento fornece demonstrações em vídeo das integrações e validações da solução.



== Casos de uso

A solução VMware Tanzu com NetApp foi arquitetada para oferecer valor excepcional para clientes com os seguintes casos de uso:

* Ofertas fáceis de implantar e gerenciar do VMware Tanzu Kubernetes Grid implantadas no VMware vSphere e integradas aos sistemas de armazenamento da NetApp .
* O poder combinado de contêineres empresariais e cargas de trabalho virtualizadas com as ofertas do VMware Tanzu Kubernetes Grid.
* Configuração do mundo real e casos de uso destacando os recursos do VMware Tanzu quando usado com o armazenamento NetApp e o conjunto de produtos NetApp Trident .
* Proteção consistente com aplicativos ou migração de cargas de trabalho em contêineres implantadas em clusters VMware Tanzu Kubernetes Grid cujos dados residem em sistemas de armazenamento NetApp usando o Trident Protect.




== Valor comercial

As empresas estão adotando cada vez mais práticas de DevOps para criar novos produtos, encurtar ciclos de lançamento e adicionar novos recursos rapidamente.  Devido à sua natureza ágil inata, contêineres e microsserviços desempenham um papel crucial no suporte às práticas de DevOps.  No entanto, praticar DevOps em escala de produção em um ambiente corporativo apresenta seus próprios desafios e impõe certos requisitos à infraestrutura subjacente, como os seguintes:

* Alta disponibilidade em todas as camadas da pilha
* Facilidade de procedimentos de implantação
* Operações e atualizações não disruptivas
* Infraestrutura programável e orientada por API para acompanhar a agilidade dos microsserviços
* Multilocação com garantias de desempenho
* Capacidade de executar cargas de trabalho virtualizadas e em contêineres simultaneamente
* Capacidade de dimensionar a infraestrutura de forma independente com base nas demandas da carga de trabalho
* Capacidade de implantação em um modelo de nuvem híbrida com contêineres em execução em data centers locais e na nuvem.


O VMware Tanzu com NetApp reconhece esses desafios e apresenta uma solução que ajuda a resolver cada preocupação implantando as ofertas do VMware Tanzu Kubernetes no ambiente de nuvem híbrida escolhido pelo cliente.



== Visão geral da tecnologia

A solução VMware Tanzu com NetApp é composta pelos seguintes componentes principais:



=== Plataformas VMware Tanzu Kubernetes

O VMware Tanzu está disponível em uma variedade de versões que a equipe de engenharia de soluções da NetApp validou em nossos laboratórios.  Cada versão do Tanzu integra-se com sucesso ao portfólio de armazenamento da NetApp e cada uma pode ajudar a atender a determinadas demandas de infraestrutura.  Os destaques com marcadores a seguir descrevem os recursos e ofertas de cada versão do Tanzu descrita neste documento.

*Grade VMware Tanzu Kubernetes (TKG)*

* Ambiente Kubernetes upstream padrão implantado em um ambiente VMware vSphere.
* Anteriormente conhecido como Essential PKS (da aquisição da Heptio, fevereiro de 2019).
* O TKG é implantado com uma instância de cluster de gerenciamento separada para suporte no vSphere 6.7U3 em diante.
* As implantações do TKG também podem ser implantadas na nuvem com AWS ou Azure.
* Permite o uso de nós de trabalho do Windows ou Linux (Ubuntu/Photon).
* NSX-T, proxy HA, rede AVI ou balanceadores de carga podem ser usados para o plano de controle.
* O TKG oferece suporte ao MetalLB para o plano de aplicação/dados.
* Pode usar o vSphere CSI, bem como CSIs de terceiros, como o NetApp Trident.


*Serviço de grade VMware Tanzu Kubernetes (TKGS)*

* Ambiente Kubernetes upstream padrão implantado em um ambiente VMware vSphere.
* Anteriormente conhecido como Essential PKS (da aquisição da Heptio, fevereiro de 2019).
* TKGS implantado com cluster de supervisor e clusters de carga de trabalho somente no vSphere 7.0U1 em diante.
* Permite o uso de nós de trabalho do Windows ou Linux (Ubuntu/Photon).
* NSX-T, proxy HA, rede AVI ou balanceadores de carga podem ser usados para o plano de controle.
* O TKGS suporta MetalLB para plano de aplicação/dados.
* Pode usar o vSphere CSI, bem como CSIs de terceiros, como o NetApp Trident.
* Fornece suporte para vSphere Pods com Tanzu, permitindo que os pods sejam executados diretamente em hosts ESXi habilitados no ambiente.


*VMWare Tanzu Kubernetes Grid Integrado (TKGI)*

* Anteriormente conhecido como Enterprise PKS (da aquisição da Heptio, fevereiro de 2019).
* Pode usar NSX-T, HA Proxy ou Avi.  Você também pode fornecer seu próprio balanceador de carga.
* Suportado a partir do vSphere 6.7U3, bem como AWS, Azure e GCP.
* Configuração via assistente para permitir facilidade de implantação.
* Executa o Tanzu em VMs imutáveis controladas e gerenciadas pelo BOSH.
* Pode usar o vSphere CSI, bem como CSIs de terceiros, como o NetApp Trident (algumas condições se aplicam).


*vSphere com Tanzu (vSphere Pods)*

* Os pods nativos do vSphere são executados em uma camada fina baseada em fótons com hardware virtual prescrito para isolamento completo.
* Requer NSX-T, mas isso permite suporte a recursos adicionais, como um registro de imagem Harbor.
* Implantado e gerenciado no vSphere 7.0U1 em diante usando um cluster de Supervisor virtual como o TKGS.  Executa pods diretamente em nós ESXi.
* Totalmente integrado ao vSphere, maior visibilidade e controle pela administração do vSphere.
* Pods isolados baseados em CRX para o mais alto nível de segurança.
* Suporta somente vSphere CSI para armazenamento persistente.  Não há suporte para orquestradores de armazenamento de terceiros.




=== Sistemas de armazenamento NetApp

A NetApp tem vários sistemas de armazenamento perfeitos para data centers empresariais e implantações de nuvem híbrida.  O portfólio da NetApp inclui os sistemas de armazenamento NetApp ONTAP, NetApp Element e NetApp e-Series, todos os quais podem fornecer armazenamento persistente para aplicativos em contêineres.

Para obter mais informações, visite o site da NetApp https://www.netapp.com["aqui"] .



=== Integrações de armazenamento NetApp

O Trident é um orquestrador de armazenamento de código aberto e totalmente suportado para contêineres e distribuições Kubernetes, incluindo VMware Tanzu.

Para mais informações, visite o site da Trident https://docs.netapp.com/us-en/trident/index.html["aqui"] .



== Matriz de suporte atual para versões validadas

|===


| Tecnologia | Propósito | Versão do software 


| NetApp ONTAP | Armazenar | 9.9.1 


| NetApp Trident | Orquestração de Armazenamento | 22.04.0 


| VMware Tanzu Kubernetes Grid | Orquestração de contêineres | 1.4+ 


.2+| Serviço de grade VMware Tanzu Kubernetes .2+| Orquestração de contêineres | 0.0.15 [Espaços para nomes do vSphere] 


| 1.22.6 [Cluster de Supervisores Kubernetes] 


| VMware Tanzu Kubernetes Grid integrado | Orquestração de contêineres | 1.13.3 


| VMware vSphere | Virtualização de data center | 7.0U3 


| Centro de dados VMware NSX-T | Rede e Segurança | 3.1.3 


| Balanceador de carga avançado do VMware NSX | Balanceador de carga | 20.1.3 
|===