---
sidebar: sidebar 
permalink: anthos/anthos-storint-overview.html 
keywords: Trident, Trident, persistent storage 
summary: A NetApp fornece diversos produtos que auxiliam nossos clientes a orquestrar e gerenciar dados persistentes em ambientes baseados em contêineres, como o Anthos. 
---
= Visão geral da integração do NetApp Storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A NetApp fornece diversos produtos que auxiliam nossos clientes a orquestrar e gerenciar dados persistentes em ambientes baseados em contêineres, como o Anthos.



[[anthos-ready-storage-partner-program]]
== Programa de parceiros de armazenamento Anthos Ready.

O Google Cloud solicita periodicamente a validação atualizada das integrações de armazenamento de parceiros com novas versões do Anthos por meio do programa de parceiros de armazenamento Anthos Ready.  Uma lista de soluções de armazenamento atualmente validadas, drivers CSI, recursos disponíveis e versões do Anthos com suporte podem ser encontradas https://cloud.google.com/anthos/docs/resources/partner-storage["aqui"^] .

A NetApp manteve a conformidade regular trimestral com solicitações para validar nosso orquestrador de armazenamento compatível com Trident CSI e nosso sistema de armazenamento ONTAP com versões do Anthos.

A tabela a seguir contém as versões do Anthos testadas pela NetApp e engenheiros parceiros da NetApp para validação dos drivers e conjuntos de recursos do NetApp Trident CSI como parte do programa de parceiros de armazenamento Anthos Ready:

|===


| Tipo de implantação | Versão | Sistema de armazenamento | Versão Trident | Protocolo | Características 


| VMware | 1,28 | ONTAP 9.12.1 | 24,02 | NAS | Multiwriter, Expansão de Volume, SnapShots, PVCDataSource 


| VMware | 1,28 | ONTAP 9.12.1 | 24,02 | SAN | Bloco bruto, expansão de volume, instantâneos, PVCDataSource 


| VMware | 1,15 | ONTAP 9.12.1 | 23,04 | NAS | Multiwriter, Expansão de Volume, SnapShots, PVCDataSource 


| VMware | 1,15 | ONTAP 9.12.1 | 23,04 | SAN | Bloco bruto, expansão de volume, instantâneos, PVCDataSource 


| VMware | 1,14 | ONTAP 9.12.1 | 23,01 | NAS | Multiwriter, Expansão de Volume, SnapShots, PVCDataSource 


| VMware | 1,14 | ONTAP 9.12.1 | 23,01 | SAN | Bloco bruto, expansão de volume, instantâneos, PVCDataSource 


| VMware | 1,13 | ONTAP 9.12.1 | 22,10 | NAS | Multiwriter, Expansão de Volume, SnapShots, PVCDataSource 


| VMware | 1,13 | ONTAP 9.12.1 | 22,10 | SAN | Bloco bruto, expansão de volume, instantâneos, PVCDataSource 


| VMware | 1,11 | ONTAP 9.9.1 | 22,04 | NAS | Multiwriter, Expansão de Volume, SnapShots 


| VMware | 1,11 | ONTAP 9.9.1 | 22,04 | SAN | Bloco bruto, expansão de volume, instantâneos 


| VMware | 1,11 | Elemento 12.3 | 22,04 | SAN | Bloco bruto, expansão de volume, instantâneos 


| metal puro | 1,10 | ONTAP 9.8 | 22,01 | NAS | Multiwriter, Expansão de Volume, SnapShots 


| metal puro | 1,10 | ONTAP 9.8 | 22,01 | SAN | Bloco bruto, expansão de volume, instantâneos 
|===


[[netapp-storage-integrations]]
== Integrações de armazenamento NetApp

A NetApp fornece diversos produtos para ajudar você a orquestrar e gerenciar dados persistentes em ambientes baseados em contêineres, como o Anthos.

NetApp Trident é um orquestrador de storage de código aberto e com suporte completo para contêineres e distribuições Kubernetes, incluindo o Anthos. Para mais informações, visite o link:https://docs.netapp.com/us-en/trident/index.html["Documentação do Trident"^].

As páginas a seguir contêm informações adicionais sobre os produtos NetApp que foram validados para gerenciamento de aplicativos e armazenamento persistente na solução Anthos com NetApp .
