---
sidebar: sidebar 
permalink: anthos/anthos-trident-ontap-iscsi.html 
summary: Para habilitar a integração do Trident com o sistema de armazenamento NetApp ONTAP , você deve criar um backend que permita a comunicação com o sistema de armazenamento. 
keywords: Trident, Trident, ONTAP, AFF, FAS, iSCSI 
---
= Configuração do NetApp ONTAP iSCSI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para habilitar a integração do Trident com o sistema de armazenamento NetApp ONTAP , você deve criar um backend que permita a comunicação com o sistema de armazenamento.

. Existem arquivos de backend de amostra disponíveis no arquivo de instalação baixado no `sample-input` hierarquia de pastas.  Para sistemas NetApp ONTAP que atendem iSCSI, copie o `backend-ontap-san.json` arquivo para seu diretório de trabalho e edite o arquivo.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/backends-samples/ontap-san/backend-ontap-san.json ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi backend-ontap-san.json
----
. Edite os valores managementLIF, dataLIF, svm, username e password neste arquivo.
+
[listing]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "managementLIF": "172.21.224.201",
  "dataLIF": "10.61.181.240",
  "svm": "trident_svm",
  "username": "admin",
  "password": "password"
}
----
. Com esse arquivo de backend em vigor, execute o seguinte comando para criar seu primeiro backend.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ ./tridentctl -n trident create backend -f backend-ontap-san.json
+------------------------+----------------+--------------------------------------+--------+---------+
|          NAME          | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+------------------------+----------------+--------------------------------------+--------+---------+
| ontapsan_10.61.181.241 | ontap-san      | 6788533c-7fea-4a35-b797-fb9bb3322b91 | online |       0 |
+------------------------+----------------+--------------------------------------+--------+---------+
----
. Com o backend criado, você deve criar uma classe de armazenamento.  Assim como no backend, há um arquivo de classe de armazenamento de exemplo que pode ser editado para o ambiente disponível na pasta sample-inputs.  Copie-o para o diretório de trabalho e faça as edições necessárias para refletir o backend criado.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi storage-class-basic.yaml
----
. A única edição que deve ser feita neste arquivo é definir o `backendType` valor para o nome do driver de armazenamento do backend recém-criado.  Observe também o valor do campo nome, que deve ser referenciado em uma etapa posterior.
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
----
+

NOTE: Existe um campo opcional chamado `fsType` que é definido neste arquivo.  Em backends iSCSI, esse valor pode ser definido para um tipo específico de sistema de arquivos Linux (XFS, ext4 e assim por diante) ou pode ser excluído para permitir que o sistema operacional do nó de trabalho decida qual sistema de arquivos usar.

. Execute o `kubectl` comando para criar a classe de armazenamento.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. Com a classe de armazenamento criada, você deve criar a primeira reivindicação de volume persistente (PVC).  Há uma amostra `pvc-basic.yaml` arquivo que pode ser usado para executar esta ação localizado também em sample-inputs.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi pvc-basic.yaml
----
. A única edição que deve ser feita neste arquivo é garantir que o `storageClassName` campo corresponde ao que acabou de ser criado.  A definição de PVC pode ser ainda mais personalizada conforme exigido pela carga de trabalho a ser provisionada.
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. Crie o PVC emitindo o `kubectl` comando.  A criação pode levar algum tempo dependendo do tamanho do volume de apoio que está sendo criado, então você pode acompanhar o processo conforme ele é concluído.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-7ceac1ba-0189-43c7-8f98-094719f7956c   1Gi        RWO            basic-csi      3s
----

