---
sidebar: sidebar 
permalink: videos/tanzu-videos.html 
keywords: video, demonstration, deployment, VMware Tanzu with NetApp, NetApp, Tanzu 
summary: Esta página contém links para vídeos que demonstram alguns dos recursos descritos neste documento. 
---
= Assista a vídeos sobre o VMware Tanzu com NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Explore a integração do VMware Tanzu com o NetApp por meio de uma série de vídeos que demonstram recursos importantes, como provisionamento de armazenamento persistente, clonagem de aplicativos e proteção de dados usando o Trident.


NOTE: Essas demos foram gravadas como uma prévia técnica usando a versão 1.3.1 do TKG e a versão 21.12 do Trident Protect.  Consulte a Matriz de Suporte para ver as versões oficiais suportadas.



== Provisionamento de armazenamento persistente

.Use o Trident para provisionar armazenamento persistente no VMware Tanzu - VMware Tanzu com NetApp
video::8db3092b-3468-4754-b2d7-b01200fbb38d[panopto,width=360]


== Clonagem de aplicativos e proteção de dados

.Use o Trident Protect para clonar aplicativos no VMWare Tanzu - VMware Tanzu com NetApp
video::01aff358-a0a2-4c4f-9062-b01200fb9abd[panopto,width=360]