---
sidebar: sidebar 
permalink: openshift/os-adv-mgmt-deployment-prereq.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, ONTAP, Trident, Red Hat OpenShift, Advanced Cluster Management, Advanced Cluster Management for Kubernetes 
summary: Gerenciamento avançado de cluster para Kubernetes no Red Hat OpenShift com NetApp 
---
= Implantar o Advanced Cluster Management para Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta seção aborda o gerenciamento avançado de cluster para Kubernetes no Red Hat OpenShift com NetApp.



[[prerequisites]]
== Pré-requisitos

. Um cluster Red Hat OpenShift (maior que a versão 4.5) para o cluster do hub
. Clusters Red Hat OpenShift (superiores à versão 4.4.3) para clusters gerenciados
. Acesso de administrador de cluster ao cluster Red Hat OpenShift
. Uma assinatura do Red Hat para Advanced Cluster Management para Kubernetes


O Advanced Cluster Management é um complemento para o cluster OpenShift, portanto, existem certos requisitos e restrições nos recursos de hardware com base nos recursos usados no hub e nos clusters gerenciados. Você precisa levar esses fatores em consideração ao dimensionar os clusters. Veja link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html-single/install/index#network-configuration["Requisitos de configuração de rede"^] para mais detalhes.

Opcionalmente, se o cluster central tiver nós dedicados para hospedar componentes de infraestrutura e você quiser instalar recursos de Advanced Cluster Management apenas nesses nós, você precisa adicionar tolerâncias e seletores a esses nós conforme necessário. Para mais detalhes, consulte link:https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html/install/installing#installing-on-infra-node["Instalação em nós de infraestrutura"^].
