---
sidebar: sidebar 
permalink: openshift/os-adv-mgmt-deployment-prereq.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, ONTAP, Trident, Red Hat OpenShift, Advanced Cluster Management, Advanced Cluster Management for Kubernetes 
summary: Gerenciamento avançado de cluster para Kubernetes no Red Hat OpenShift com NetApp 
---
= Implantar o Advanced Cluster Management para Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta seção aborda o gerenciamento avançado de cluster para Kubernetes no Red Hat OpenShift com NetApp.



== Pré-requisitos

. Um cluster Red Hat OpenShift (maior que a versão 4.5) para o cluster do hub
. Clusters Red Hat OpenShift (superiores à versão 4.4.3) para clusters gerenciados
. Acesso de administrador de cluster ao cluster Red Hat OpenShift
. Uma assinatura do Red Hat para Advanced Cluster Management para Kubernetes


O Advanced Cluster Management é um complemento para o cluster OpenShift, portanto, há certos requisitos e restrições nos recursos de hardware com base nos recursos usados no hub e nos clusters gerenciados.  Você precisa levar essas questões em consideração ao dimensionar os clusters.  Veja a documentação https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html-single/install/index#network-configuration["aqui"] para mais detalhes.

Opcionalmente, se o cluster do hub tiver nós dedicados para hospedar componentes de infraestrutura e você quiser instalar recursos do Advanced Cluster Management somente nesses nós, será necessário adicionar tolerâncias e seletores a esses nós adequadamente.  Para mais detalhes, consulte a documentação https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html/install/installing#installing-on-infra-node["aqui"] .
