---
sidebar: sidebar 
permalink: openshift/os-multitenancy-overview.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, Multitenancy, Multi-tenancy 
summary: Configurando multilocação no Red Hat OpenShift com NetApp 
---
= Configurando multilocação no Red Hat OpenShift com NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Muitas organizações que executam vários aplicativos ou cargas de trabalho em contêineres tendem a implantar um cluster Red Hat OpenShift por aplicativo ou carga de trabalho.  Isso permite que eles implementem isolamento rigoroso para o aplicativo ou carga de trabalho, otimizem o desempenho e reduzam vulnerabilidades de segurança.  No entanto, implantar um cluster Red Hat OpenShift separado para cada aplicativo apresenta seu próprio conjunto de problemas.  Isso aumenta a sobrecarga operacional, tendo que monitorar e gerenciar cada cluster individualmente, aumenta os custos devido a recursos dedicados para diferentes aplicativos e prejudica a escalabilidade eficiente.

Para superar esses problemas, pode-se considerar executar todos os aplicativos ou cargas de trabalho em um único cluster do Red Hat OpenShift.  Mas, em tal arquitetura, o isolamento de recursos e as vulnerabilidades de segurança dos aplicativos são um dos maiores desafios.  Qualquer vulnerabilidade de segurança em uma carga de trabalho pode naturalmente se espalhar para outra carga de trabalho, aumentando assim a zona de impacto.  Além disso, qualquer utilização abrupta e descontrolada de recursos por um aplicativo pode afetar o desempenho de outro aplicativo, porque não há uma política de alocação de recursos por padrão.

Portanto, as organizações buscam soluções que reúnam o melhor dos dois mundos, por exemplo, permitindo que elas executem todas as suas cargas de trabalho em um único cluster e ainda oferecendo os benefícios de um cluster dedicado para cada carga de trabalho.

Uma solução eficaz é configurar a multilocação no Red Hat OpenShift.  Multilocação é uma arquitetura que permite que vários locatários coexistam no mesmo cluster com isolamento adequado de recursos, segurança e assim por diante.  Nesse contexto, um locatário pode ser visto como um subconjunto dos recursos do cluster que são configurados para serem usados por um grupo específico de usuários para uma finalidade exclusiva.  Configurar multilocação em um cluster Red Hat OpenShift oferece as seguintes vantagens:

* Uma redução no CapEx e OpEx ao permitir que os recursos do cluster sejam compartilhados
* Menor sobrecarga operacional e de gestão
* Protegendo as cargas de trabalho contra contaminação cruzada de violações de segurança
* Proteção de cargas de trabalho contra degradação inesperada de desempenho devido à contenção de recursos


Para um cluster OpenShift multilocatário totalmente realizado, cotas e restrições devem ser configuradas para recursos de cluster pertencentes a diferentes grupos de recursos: computação, armazenamento, rede, segurança e assim por diante.  Embora abordemos certos aspectos de todos os buckets de recursos nesta solução, nos concentramos nas melhores práticas para isolar e proteger os dados fornecidos ou consumidos por várias cargas de trabalho no mesmo cluster Red Hat OpenShift, configurando a multilocação em recursos de armazenamento que são alocados dinamicamente pelo Trident com suporte do NetApp ONTAP.
