---
sidebar: sidebar 
permalink: openshift/os-multitenancy-validation.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, Multitenancy, Multi-tenancy 
summary: Configurando multilocação no Red Hat OpenShift com NetApp 
---
= Validação
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para validar a arquitetura multilocatário configurada nas etapas anteriores, conclua as seguintes etapas:



[[validate-access-to-create-pvcs-or-pods-in-assigned-project]]
== Validar acesso para criar PVCs ou pods no projeto atribuído

. Efetue login como ocp-project-1-user, desenvolvedor no projeto-1.
. Verifique o acesso para criar um novo projeto.


[listing]
----
oc create ns sub-project-1
----
. Crie um PVC no projeto-1 usando a classe de armazenamento atribuída ao projeto-1.


[listing]
----
cat << EOF | oc create -f -
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-project-1
  namespace: project-1
  annotations:
    trident.netapp.io/reclaimPolicy: Retain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: project-1-sc
EOF
----
. Verifique o PV associado ao PVC.


[listing]
----
oc get pv
----
. Valide se o PV e seu volume foram criados em um SVM dedicado ao projeto-1 no NetApp ONTAP.


[listing]
----
volume show -vserver project-1-svm
----
. Crie um pod no projeto-1 e monte o PVC criado na etapa anterior.


[listing]
----
cat << EOF | oc create -f -
kind: Pod
apiVersion: v1
metadata:
  name: test-pvc-pod
  namespace: project-1
spec:
  volumes:
    - name: test-pvc-project-1
      persistentVolumeClaim:
       claimName: test-pvc-project-1
  containers:
    - name: test-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: test-pvc-project-1
EOF
----
. Verifique se o pod está em execução e se o volume foi montado.


[listing]
----
oc describe pods test-pvc-pod -n project-1
----


[[validate-access-to-create-pvcs-or-pods-in-another-project-or-use-resources-dedicated-to-another-project]]
== Validar acesso para criar PVCs ou pods em outro projeto ou usar recursos dedicados a outro projeto

. Efetue login como ocp-project-1-user, desenvolvedor no projeto-1.
. Crie um PVC no projeto-1 usando a classe de armazenamento atribuída ao projeto-2.


[listing]
----
cat << EOF | oc create -f -
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-project-1-sc-2
  namespace: project-1
  annotations:
    trident.netapp.io/reclaimPolicy: Retain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: project-2-sc
EOF
----
. Crie um PVC no projeto-2.


[listing]
----
cat << EOF | oc create -f -
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-project-2-sc-1
  namespace: project-2
  annotations:
    trident.netapp.io/reclaimPolicy: Retain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: project-1-sc
EOF
----
. Certifique-se de que os PVCs `test-pvc-project-1-sc-2` e `test-pvc-project-2-sc-1` não foram criados.


[listing]
----
oc get pvc -n project-1
oc get pvc -n project-2
----
. Crie um pod no projeto-2.


[listing]
----
cat << EOF | oc create -f -
kind: Pod
apiVersion: v1
metadata:
  name: test-pvc-pod
  namespace: project-1
spec:
  containers:
    - name: test-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
EOF
----


[[validate-access-to-view-and-edit-projects-resourcequotas-and-storageclasses]]
== Validar acesso para visualizar e editar Projetos, ResourceQuotas e StorageClasses

. Efetue login como ocp-project-1-user, desenvolvedor no projeto-1.
. Verifique o acesso para criar novos projetos.


[listing]
----
oc create ns sub-project-1
----
. Valide o acesso para visualizar projetos.


[listing]
----
oc get ns
----
. Verifique se o usuário pode visualizar ou editar ResourceQuotas no projeto-1.


[listing]
----
oc get resourcequotas -n project-1
oc edit resourcequotas project-1-sc-rq -n project-1
----
. Valide se o usuário tem acesso para visualizar as classes de armazenamento.


[listing]
----
oc get sc
----
. Verifique o acesso para descrever as classes de armazenamento.
. Valide o acesso do usuário para editar as classes de armazenamento.


[listing]
----
oc edit sc project-1-sc
----